[build]
  # La directory base del progetto
  base = "main"
  # Directory dove Netlify pubblicherà i file generati dalla build
  publish = "main/dist"
  # Comando per generare i file di build
  command = "npm run build"

[dev]
  # Specifica il framework usato (vite in questo caso)
  framework = "vite"

[functions]
  # Directory per le funzioni serverless, se usate
  directory = "functions"
